FROM python:3.8-slim
WORKDIR /app
# set environment variables
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH="${PATH}:/root/.poetry/bin" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/phrase_counter \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1



# install dependencies
RUN apt update && apt upgrade -y && apt install curl -y && apt install build-essential python3-dev -y

COPY pyproject.toml /app

# POETRY
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false
RUN poetry lock -n && poetry export --without-hashes > requirements.txt
RUN poetry install -n

COPY . /app

# Final
WORKDIR /app
CMD ["uvicorn", "phrase_counter.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
